/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package adaptavist

class App {
    static void main(String[] args) {
        if (args.length != 1) {
            println("Args missing. Try: ./gradlew run --args='<file_path>'")
            System.exit(1)
        }

        def location = args[0]
        boolean isWeb = location.startsWith("http://") || location.startsWith("https://")

        def wordCounter = new WordCounter()
        def fileReader = new FileReader()

        // Conditional call due to file origin
        def words = isWeb ? fileReader.readUrlFile(location) : fileReader.readLocalFile(location)

        wordCounter.count(words).each { entry ->
            println("${entry.key}: ${entry.value}")
        }
    }
}
