/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
package adaptavist

import spock.lang.Specification

class AppTest extends Specification {
    WordCounter wordCounter = Spy()
    FileReader fileReader = Spy()

    def "main method should call WordCounter.count with correct words for local file"() {

        given:
        def location = 'src/test/resources/mocked_file.txt'
        def fileContent = ['this', 'is', 'is', 'a', 'test', 'file', 'file']
        def args = [location]

        when:
        App.main(*args)

        then:
        fileReader.readLocalFile(location) == fileContent
        def countedWords = wordCounter.count(fileContent)

        assert countedWords.find { it.key == 'file' }.value == 2
    }

    def "main method should call WordCounter.count with correct words for URL"() {
        given:
        def location = 'http://example.com'
        def args = [location]

        when:
        App.main(*args)

        then:
        assert fileReader.readUrlFile(location).contains('doctype')
    }
}